import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import ReduxProvider from '@/components/ReduxProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-screen h-screen overflow-auto flex flex-col'>
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
