import {Nunito} from 'next/font/google'

import Header from '@/components/Header'
import './globals.css'
import type {Metadata} from 'next'
import {Provider} from 'react-redux'
import {store} from '@/redux/store'
import ReduxProvider from '@/components/ReduxProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const font = Nunito({
    subsets: ['latin'],
});

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={font.className}>
        <ReduxProvider>
            <Header/>
            <div className="px-0 lg:px-40 2xl:px-80 py-24">
                {children}
            </div>
        </ReduxProvider>
        </body>
        </html>
    )
}
